### ISSUE TITLE
This plugin not work on Quiz question attempt page

### ISSUE THREAD

**Issue by nileshnpathade** [jcorel/moodle-block_timestat#13]
Hi Developer,

Please help me, I am using this plugin, but its not working at Quiz attempts page when I have added this block on course view page and set as display to Any page.

As a admin I can see this block at Quiz attempts BUT AS STUDENT WHEN GIVES / ATTEMPTS AND STUDENT WILL ATTEMPTING IT THAT TIME TIMER NOT WORKING.

please help me 

Its very urgent.

**Comment by jcorel** [comment]
Hello nileshnpathade,

The student doesn't have permission to view the block, but the time does count anyway. Have you checked?

**Comment by nileshnpathade** [comment]
Yes, 
I have to set as Block show configre  in Quiz setting. then it works for me.
please add a comments for block document for Quiz attempt page need to configure quiz setting as show blocks on attempt page.
Thank you for replying.
