### ISSUE TITLE
At a time multiple calls called 

### ISSUE THREAD

**Issue by nileshnpathade** [jcorel/moodle-block_timestat#14]
Hi Developers, 

Thank you for developing Great plugin. 
But I am facing the issue with time capturing calls. it call api on multiple times. So it hits to my databased every 15 sec 4 calls to database.

Please reload multiple time page then check.

**Comment by nileshnpathade** [comment]
![image](https://user-images.githubusercontent.com/13468332/206160137-07177e3c-4433-420c-809f-fdf33241661d.png)

**Comment by jcorel** [comment]
Hi nileshnpathade,

You are correct. Unfortunately, this method of counting time "in real time" has a drawback: it can put a lot of strain on the database. The advantage is that it provides a more precise time calculation. If you don't need such high accuracy, you may want to consider using the "Course dedication" block instead. This will help avoid overloading the database.

https://moodle.org/plugins/block_dedication

**Comment by nileshnpathade** [comment]
Thank you for replying and suggesting block. 
May I know this block can show me which user how time spend on each activity in course.

**Comment by jcorel** [comment]
As far as I know the only function of Course dedication  is to provide course time. I'm sorry!

**Comment by nileshnpathade** [comment]
Thank you for supports.
