### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [jcorel/moodle-block_timestat#7]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privaci api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Note - this is NOT a blocker for plugins db approval.

**Comment by mudrd8mz** [comment]
I am confused now. The version 2022032901 uploaded to the plugins directory has some implementation of the privacy API present (with some minor issues such as wrong `@copyright` holder name. However, that is not present in the git repository here.

Also, the version currently present in the plugins directory still contains the `update_register.php` file which I understood was supposed to be replaced by an external function `block_timestat_update_register`
